### ISSUE TITLE
Dashboard styles don't work

### ISSUE THREAD

**Issue by tosbaha** [90milesbridge/react-rainbow-admin#53]
Hi,
I cloned the master branch and did npm install and npm start. However in the dashboard page, badge styles are not applied. Badge color is grayed and it seems it is overridden by other styles. Firebase version correctly shows the colors.
I added screenshots.

Firebase
=== 
<img width="1232" alt="Screen Shot 2019-03-18 at 16 13 44" src="https://user-images.githubusercontent.com/971530/54532457-d772ea80-4998-11e9-84d6-2d61558a796a.png">

Master Repo
=== 
<img width="1225" alt="Screen Shot 2019-03-18 at 16 13 33" src="https://user-images.githubusercontent.com/971530/54532458-d80b8100-4998-11e9-885b-86f53e36fc61.png">

**Comment by TahimiLeonBravo** [comment]
thanks @tosbaha, Weird. `react-create-app` compiles differently in prod and dev mode. If you check you can see that in prod is working correctly!
As a work around  we are gonna add `!important` to the color rule. Until we find a better solution.
good catch!!
